; generated by ARM C/C++ Compiler, 4.1 [Build 791]
; commandline ArmCC [--debug -c --asm -ointerrupciones_servos.o --depend=interrupciones_servos.d --cpu=Cortex-M3 --apcs=interwork -O0 -IC:\Keil\ARM\CMSIS\Include -IC:\Keil\ARM\INC\NXP\LPC17xx --omf_browse=interrupciones_servos.crf SERVOS\interrupciones_servos.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

TIMER0_IRQHandler PROC
        PUSH     {r4,lr}
        MOV      r0,#0x40004000
        LDR      r0,[r0,#0]
        TST      r0,#2
        BEQ      |L1.268|
        MOV      r0,#0xff
        MOV      r1,#0x40004000
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        MOV      r1,#0x2710
        ADD      r0,r0,r1
        MOV      r1,#0x40004000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        ADD      r0,r0,#0x3e8
        STR      r0,[r1,#0x20]
        LDR      r0,|L1.504|
        LDRB     r0,[r0,#0]  ; modo
        CMP      r0,#1
        BNE      |L1.138|
        LDR      r0,|L1.508|
        LDR      r0,[r0,#0]  ; resul_1
        BL       __aeabi_ui2f
        LDR      r1,|L1.512|
        STR      r0,[r1,#0]  ; ADC_value_Azim
        LDR      r1,|L1.516|
        LDR      r0,|L1.512|
        LDR      r0,[r0,#0]  ; ADC_value_Azim
        BL       __aeabi_fdiv
        LDR      r1,|L1.520|
        STR      r0,[r1,#0]  ; x
        LDR      r1,|L1.516|
        LDR      r0,|L1.512|
        LDR      r0,[r0,#0]  ; ADC_value_Azim
        BL       __aeabi_fdiv
        LDR      r1,|L1.524|
        STR      r0,[r1,#0]  ; ADC_x
        LDR      r0,|L1.528|
        LDR      r0,[r0,#0]  ; resul_2
        BL       __aeabi_ui2f
        LDR      r1,|L1.532|
        STR      r0,[r1,#0]  ; ADC_value_Alt
        LDR      r1,|L1.516|
        LDR      r0,|L1.532|
        LDR      r0,[r0,#0]  ; ADC_value_Alt
        BL       __aeabi_fdiv
        LDR      r1,|L1.536|
        STR      r0,[r1,#0]  ; ADC_y
        LDR      r1,|L1.516|
        LDR      r0,|L1.532|
        LDR      r0,[r0,#0]  ; ADC_value_Alt
        BL       __aeabi_fdiv
        LDR      r1,|L1.540|
        STR      r0,[r1,#0]  ; y
|L1.138|
        LDR      r0,|L1.504|
        LDRB     r0,[r0,#0]  ; modo
        CMP      r0,#0
        BNE      |L1.336|
        LDR      r0,|L1.544|
        LDR      r0,[r0,#0]  ; cons_pro_x_cam
        LDR      r1,|L1.548|
        STR      r0,[r1,#0]  ; cons_pro_x
        LDR      r0,|L1.552|
        LDR      r0,[r0,#0]  ; cons_pro_y_cam
        LDR      r1,|L1.556|
        STR      r0,[r1,#0]  ; cons_pro_y
        MOV      r0,#0x3f000000
        LDR      r1,|L1.560|
        STR      r0,[r1,#0]  ; cons_dif_x
        LDR      r1,|L1.564|
        STR      r0,[r1,#0]  ; cons_dif_y
        LDR      r0,|L1.508|
        LDR      r0,[r0,#0]  ; resul_1
        BL       __aeabi_ui2f
        LDR      r1,|L1.512|
        STR      r0,[r1,#0]  ; ADC_value_Azim
        LDR      r0,|L1.568|
        LDR      r0,[r0,#0]  ; det_x
        BL       __aeabi_ui2f
        MOV      r4,r0
        LDR      r1,|L1.572|
        BL       __aeabi_fdiv
        LDR      r1,|L1.520|
        STR      r0,[r1,#0]  ; x
        LDR      r0,|L1.568|
        LDR      r0,[r0,#0]  ; det_x
        CMP      r0,#0x14
        BCC      |L1.224|
        LDR      r0,|L1.568|
        LDR      r0,[r0,#0]  ; det_x
        CMP      r0,#0x12c
        BLS      |L1.232|
|L1.224|
        MOV      r0,#0x3f000000
        LDR      r1,|L1.520|
        STR      r0,[r1,#0]  ; x
|L1.232|
        LDR      r1,|L1.516|
        LDR      r0,|L1.512|
        LDR      r0,[r0,#0]  ; ADC_value_Azim
        BL       __aeabi_fdiv
        LDR      r1,|L1.524|
        STR      r0,[r1,#0]  ; ADC_x
        MOV      r0,#0x3f000000
        LDR      r1,|L1.576|
        STR      r0,[r1,#0]  ; umbral_x
        LDR      r0,|L1.528|
        LDR      r0,[r0,#0]  ; resul_2
        BL       __aeabi_ui2f
        LDR      r1,|L1.532|
        STR      r0,[r1,#0]  ; ADC_value_Alt
        B        |L1.270|
|L1.268|
        B        |L1.340|
|L1.270|
        LDR      r1,|L1.516|
        LDR      r0,|L1.532|
        LDR      r0,[r0,#0]  ; ADC_value_Alt
        BL       __aeabi_fdiv
        LDR      r1,|L1.536|
        STR      r0,[r1,#0]  ; ADC_y
        MOV      r0,#0x3f000000
        LDR      r1,|L1.580|
        STR      r0,[r1,#0]  ; umbral_y
        LDR      r0,|L1.584|
        LDR      r0,[r0,#0]  ; det_y
        BL       __aeabi_ui2f
        MOV      r4,r0
        LDR      r1,|L1.588|
        BL       __aeabi_fdiv
        LDR      r1,|L1.540|
        STR      r0,[r1,#0]  ; y
        LDR      r0,|L1.584|
        LDR      r0,[r0,#0]  ; det_y
        CMP      r0,#0x14
        BCC      |L1.328|
        LDR      r0,|L1.584|
        LDR      r0,[r0,#0]  ; det_y
        CMP      r0,#0xdc
        BLS      |L1.336|
|L1.328|
        MOV      r0,#0x3f000000
        LDR      r1,|L1.540|
        STR      r0,[r1,#0]  ; y
|L1.336|
        BL       Control_PID
|L1.340|
        MOV      r0,#0x40004000
        LDR      r0,[r0,#0]
        TST      r0,#4
        BEQ      |L1.384|
        MOV      r0,#0xff
        MOV      r1,#0x40004000
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        ADD      r0,r0,#0x3e8
        STR      r0,[r1,#0x20]
        LDR      r0,|L1.592|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.592|
        STR      r0,[r1,#0]
|L1.384|
        POP      {r4,pc}
        ENDP

ADC_IRQHandler PROC
        LDR      r1,|L1.592|
        LDR      r0,[r1,#0x30]
        LDR      r0,[r1,#4]
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0x7000000
        LDR      r2,|L1.592|
        STR      r1,[r2,#0]
        MOV      r1,r2
        LDR      r1,[r1,#0x20]
        MOV      r2,#1
        AND      r1,r2,r1,LSR #31
        CMP      r1,#1
        BNE      |L1.454|
        LDR      r1,|L1.592|
        LDR      r1,[r1,#0x20]
        UBFX     r1,r1,#6,#10
        LDR      r2,|L1.508|
        STR      r1,[r2,#0]  ; resul_1
        LDR      r1,|L1.592|
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0x10
        LDR      r2,|L1.592|
        STR      r1,[r2,#0]
        MOV      r1,r2
        LDR      r1,[r1,#0]
        ORR      r1,r1,#0x20
        STR      r1,[r2,#0]
        B        |L1.502|
|L1.454|
        LDR      r1,|L1.592|
        LDR      r1,[r1,#0x24]
        MOVS     r2,#1
        AND      r1,r2,r1,LSR #31
        CMP      r1,#1
        BNE      |L1.502|
        LDR      r1,|L1.592|
        LDR      r1,[r1,#0x24]
        UBFX     r1,r1,#6,#10
        LDR      r2,|L1.528|
        STR      r1,[r2,#0]  ; resul_2
        LDR      r1,|L1.592|
        LDR      r1,[r1,#0]
        BIC      r1,r1,#0x20
        LDR      r2,|L1.592|
        STR      r1,[r2,#0]
        MOV      r1,r2
        LDR      r1,[r1,#0]
        ORR      r1,r1,#0x10
        STR      r1,[r2,#0]
|L1.502|
        BX       lr
        ENDP

|L1.504|
        DCD      modo
|L1.508|
        DCD      resul_1
|L1.512|
        DCD      ADC_value_Azim
|L1.516|
        DCD      0x447fc000
|L1.520|
        DCD      x
|L1.524|
        DCD      ADC_x
|L1.528|
        DCD      resul_2
|L1.532|
        DCD      ADC_value_Alt
|L1.536|
        DCD      ADC_y
|L1.540|
        DCD      y
|L1.544|
        DCD      cons_pro_x_cam
|L1.548|
        DCD      cons_pro_x
|L1.552|
        DCD      cons_pro_y_cam
|L1.556|
        DCD      cons_pro_y
|L1.560|
        DCD      cons_dif_x
|L1.564|
        DCD      cons_dif_y
|L1.568|
        DCD      det_x
|L1.572|
        DCD      0x43a00000
|L1.576|
        DCD      umbral_x
|L1.580|
        DCD      umbral_y
|L1.584|
        DCD      det_y
|L1.588|
        DCD      0x43700000
|L1.592|
        DCD      0x40034000

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "SERVOS\\interrupciones_servos.c"
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___23_interrupciones_servos_c_00629a03____REV16|
#line 114 "C:\\Keil\\ARM\\CMSIS\\Include\\core_cmInstr.h"
|__asm___23_interrupciones_servos_c_00629a03____REV16| PROC
#line 115

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___23_interrupciones_servos_c_00629a03____REVSH|
#line 128
|__asm___23_interrupciones_servos_c_00629a03____REVSH| PROC
#line 129

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT TIMER0_IRQHandler [CODE]
        EXPORT ADC_IRQHandler [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __aeabi_ui2f [CODE]
        IMPORT __aeabi_fdiv [CODE]
        IMPORT Control_PID [CODE]
        IMPORT modo [DATA]
        IMPORT resul_1 [DATA]
        IMPORT ADC_value_Azim [DATA]
        IMPORT x [DATA]
        IMPORT ADC_x [DATA]
        IMPORT resul_2 [DATA]
        IMPORT ADC_value_Alt [DATA]
        IMPORT ADC_y [DATA]
        IMPORT y [DATA]
        IMPORT cons_pro_x_cam [DATA]
        IMPORT cons_pro_x [DATA]
        IMPORT cons_pro_y_cam [DATA]
        IMPORT cons_pro_y [DATA]
        IMPORT cons_dif_x [DATA]
        IMPORT cons_dif_y [DATA]
        IMPORT det_x [DATA]
        IMPORT umbral_x [DATA]
        IMPORT umbral_y [DATA]
        IMPORT det_y [DATA]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
