; generated by ARM C/C++ Compiler, 4.1 [Build 791]
; commandline ArmCC [--debug -c --asm -olpc17xx_pinsel.o --depend=lpc17xx_pinsel.d --cpu=Cortex-M3 --apcs=interwork -O0 -IC:\Keil\ARM\CMSIS\Include -IC:\Keil\ARM\INC\NXP\LPC17xx --omf_browse=lpc17xx_pinsel.crf lpc17xx_pinsel.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

set_PinFunc PROC
        PUSH     {r4-r7,lr}
        MOV      r4,r0
        MOV      r3,r1
        MOV      r5,r2
        MOV      r1,r3
        LSL      r0,r4,#1
        LDR      r2,|L1.292|
        CMP      r1,#0x10
        BCC      |L1.28|
        SUB      r1,r1,#0x10
        ADD      r0,r0,#1
|L1.28|
        LDR      r6,[r2,r0,LSL #2]
        LSL      r12,r1,#1
        MOV      r7,#3
        LSL      r7,r7,r12
        BIC      r6,r6,r7
        STR      r6,[r2,r0,LSL #2]
        LDR      r6,[r2,r0,LSL #2]
        LSL      r7,r1,#1
        LSL      r7,r5,r7
        ORR      r6,r6,r7
        STR      r6,[r2,r0,LSL #2]
        POP      {r4-r7,pc}
        ENDP

set_ResistorMode PROC
        PUSH     {r4-r7,lr}
        MOV      r4,r0
        MOV      r3,r1
        MOV      r5,r2
        MOV      r1,r3
        LSL      r0,r4,#1
        LDR      r2,|L1.296|
        CMP      r1,#0x10
        BCC      |L1.102|
        SUB      r1,r1,#0x10
        ADD      r0,r0,#1
|L1.102|
        LDR      r6,[r2,r0,LSL #2]
        LSL      r12,r1,#1
        MOV      r7,#3
        LSL      r7,r7,r12
        BIC      r6,r6,r7
        STR      r6,[r2,r0,LSL #2]
        LDR      r6,[r2,r0,LSL #2]
        LSL      r7,r1,#1
        LSL      r7,r5,r7
        ORR      r6,r6,r7
        STR      r6,[r2,r0,LSL #2]
        POP      {r4-r7,pc}
        ENDP

set_OpenDrainMode PROC
        PUSH     {r4,r5,lr}
        MOV      r3,r1
        LDR      r1,|L1.300|
        CMP      r2,#1
        BNE      |L1.180|
        LDR      r4,[r1,r0,LSL #2]
        MOV      r5,#1
        LSL      r5,r5,r3
        ORR      r4,r4,r5
        STR      r4,[r1,r0,LSL #2]
        B        |L1.200|
|L1.180|
        LDR      r4,[r1,r0,LSL #2]
        MOV      r5,#1
        LSL      r5,r5,r3
        BIC      r4,r4,r5
        STR      r4,[r1,r0,LSL #2]
|L1.200|
        POP      {r4,r5,pc}
        ENDP

PINSEL_ConfigTraceFunc PROC
        CMP      r0,#1
        BNE      |L1.220|
        LDR      r1,|L1.292|
        LDR      r1,[r1,#0x28]
        ORR      r1,r1,#8
        LDR      r2,|L1.292|
        STR      r1,[r2,#0x28]
        B        |L1.234|
|L1.220|
        CBNZ     r0,|L1.234|
        LDR      r1,|L1.292|
        LDR      r1,[r1,#0x28]
        BIC      r1,r1,#8
        LDR      r2,|L1.292|
        STR      r1,[r2,#0x28]
|L1.234|
        BX       lr
        ENDP

PINSEL_SetI2C0Pins PROC
        CMP      r0,#1
        BNE      |L1.244|
        MOV      r2,#5
|L1.244|
        CBNZ     r1,|L1.250|
        MOV      r2,#0xa
|L1.250|
        LDR      r3,|L1.292|
        STR      r2,[r3,#0x7c]
        BX       lr
        ENDP

PINSEL_ConfigPin PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        LDRB     r2,[r4,#2]
        LDRB     r1,[r4,#1]
        LDRB     r0,[r4,#0]
        BL       set_PinFunc
        LDRB     r2,[r4,#3]
        LDRB     r1,[r4,#1]
        LDRB     r0,[r4,#0]
        BL       set_ResistorMode
        LDRB     r2,[r4,#4]
        LDRB     r1,[r4,#1]
        LDRB     r0,[r4,#0]
        BL       set_OpenDrainMode
        POP      {r4,pc}
        ENDP

|L1.292|
        DCD      0x4002c000
|L1.296|
        DCD      0x4002c040
|L1.300|
        DCD      0x4002c068

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "lpc17xx_pinsel.c"
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___16_lpc17xx_pinsel_c_5ef00b0e____REV16|
#line 114 "C:\\Keil\\ARM\\CMSIS\\Include\\core_cmInstr.h"
|__asm___16_lpc17xx_pinsel_c_5ef00b0e____REV16| PROC
#line 115

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___16_lpc17xx_pinsel_c_5ef00b0e____REVSH|
#line 128
|__asm___16_lpc17xx_pinsel_c_5ef00b0e____REVSH| PROC
#line 129

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT PINSEL_ConfigTraceFunc [CODE]
        EXPORT PINSEL_SetI2C0Pins [CODE]
        EXPORT PINSEL_ConfigPin [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP set_PinFunc
        KEEP set_ResistorMode
        KEEP set_OpenDrainMode

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
