; generated by ARM C/C++ Compiler, 4.1 [Build 791]
; commandline ArmCC [--debug -c --asm -onet_config.o --depend=net_config.d --cpu=Cortex-M3 --apcs=interwork -O0 -IC:\Keil\ARM\CMSIS\Include -IC:\Keil\ARM\INC\NXP\LPC17xx --omf_browse=net_config.crf WEBSERVER\Configuration_files\Net_Config.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=1

sys_error PROC
        CMP      r0,#7
        BCS      |L1.28|
        TBB      [pc,r0]
        DCB      0x04,0x05,0x06,0x0a
        DCB      0x07,0x08,0x09,0x00
        B        |L1.28|
        B        |L1.28|
        B        |L1.28|
        B        |L1.28|
        B        |L1.28|
        NOP      
|L1.28|
        NOP      
        NOP      
|L1.32|
        B        |L1.32|
        ENDP

init_system PROC
        PUSH     {r4,lr}
        BL       eth_init_link
        BL       ip_init
        BL       icmp_init
        BL       udp_init
        BL       tcp_init
        BL       http_init
        BL       nbns_init
        POP      {r4,lr}
        B.W      dhcp_init
        ENDP

run_system PROC
        PUSH     {r4,lr}
        BL       eth_run_link
        BL       ip_run_local
        BL       icmp_run_engine
        BL       tcp_poll_sockets
        BL       http_run_server
        POP      {r4,lr}
        B.W      dhcp_run_client
        ENDP

igmp_is_member PROC
        MOVS     r0,#0
        BX       lr
        ENDP

igmp_process PROC
        BX       lr
        ENDP

ppp_send_frame PROC
        MOVS     r0,#0
        BX       lr
        ENDP

slip_send_frame PROC
        MOVS     r0,#0
        BX       lr
        ENDP

sntp_get_time PROC
        MOVS     r0,#0
        BX       lr
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.bss||, DATA, NOINIT, ALIGN=2

mem_pool
        %        12000
arp_table
        %        140
udp_scb
        %        24
tcp_scb
        %        476
http_scb
        %        312

        AREA ||.constdata||, DATA, READONLY, ALIGN=2

nlocalm
        DCB      0xc0,0xa8,0x05,0x08
        DCB      0xc0,0xa8,0x05,0x01
        DCB      0xff,0xff,0xff,0x00
        DCB      0xc0,0xa8,0x05,0x01
        DCB      0xc2,0x19,0x02,0x82
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
        DCB      0x00,0x00,0x00,0x00
sys_config
        DCD      mem_pool
        DCD      0x00002ee0
        DCB      0x0a,0x64,0x02,0x39
        DCD      lhost_name
arp_config
        DCD      arp_table
        DCB      0x0a,0x96,0x04,0x02
        DCB      0x00,0x00,0x00,0x00
dhcp_config
        DCD      ||.conststring||
        DCB      0x00,0x00,0x00,0x00
udp_config
        DCD      udp_scb
        DCB      0x02,0x00,0x00,0x00
tcp_config
        DCD      tcp_scb
        DCB      0x07,0x05
        DCW      0x0028
        DCW      0x0002,0x0014
        DCW      0x000a,0x0078
        DCW      0x05b4,0x111c
        DCB      0x07,0x00,0x00,0x00
http_config
        DCD      http_scb
        DCB      0x06,0x01
        DCW      0x0050
        DCD      ||.conststring||
        DCD      ||.conststring||+0x1
        DCD      ||.conststring||+0x15
        DCD      http_passw

        AREA ||.conststring||, DATA, READONLY, MERGE=1, STRINGS, ALIGN=0

        DCB      0
        DCB      "Embedded WEB Server",0
        DCB      "admin",0

        AREA ||.data||, DATA, ALIGN=0

lhost_name
        DCB      0x4d,0x69,0x6e,0x69
        DCB      0x44,0x4b,0x32,0x00
        %        8
own_hw_adr
        DCB      0xe0,0xf8,0x46,0x35
        DCB      0x45,0xbc
http_passw
        DCB      0x61,0x64
        DCB      0x6d,0x69,0x6e,0x00
        %        12
        DCB      0x00,0x00

        EXPORT sys_error [CODE]
        EXPORT init_system [CODE]
        EXPORT run_system [CODE]
        EXPORT igmp_is_member [CODE]
        EXPORT igmp_process [CODE]
        EXPORT ppp_send_frame [CODE]
        EXPORT slip_send_frame [CODE]
        EXPORT sntp_get_time [CODE]
        EXPORT nlocalm [DATA,SIZE=60]
        EXPORT sys_config [DATA,SIZE=16]
        EXPORT arp_config [DATA,SIZE=12]
        EXPORT dhcp_config [DATA,SIZE=8]
        EXPORT udp_config [DATA,SIZE=8]
        EXPORT tcp_config [DATA,SIZE=24]
        EXPORT http_config [DATA,SIZE=24]
        EXPORT lhost_name [DATA,SIZE=16]
        EXPORT own_hw_adr [DATA,SIZE=6]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT eth_init_link [CODE]
        IMPORT ip_init [CODE]
        IMPORT icmp_init [CODE]
        IMPORT udp_init [CODE]
        IMPORT tcp_init [CODE]
        IMPORT http_init [CODE]
        IMPORT nbns_init [CODE]
        IMPORT dhcp_init [CODE]
        IMPORT eth_run_link [CODE]
        IMPORT ip_run_local [CODE]
        IMPORT icmp_run_engine [CODE]
        IMPORT tcp_poll_sockets [CODE]
        IMPORT http_run_server [CODE]
        IMPORT dhcp_run_client [CODE]

        KEEP mem_pool
        KEEP arp_table
        KEEP udp_scb
        KEEP tcp_scb
        KEEP http_scb
        KEEP http_passw

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
