; generated by ARM C/C++ Compiler, 4.1 [Build 791]
; commandline ArmCC [--debug -c --asm -oov7670.o --depend=ov7670.d --cpu=Cortex-M3 --apcs=interwork -O0 -IC:\Keil\ARM\CMSIS\Include -IC:\Keil\ARM\INC\NXP\LPC17xx --omf_browse=ov7670.crf OV7670\OV7670.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

ov7670_set PROC
        MOV      r2,r0
        NOP      
|L1.4|
        LDR      r0,|L1.1024|
        LDR      r0,[r0,#0]  ; I2CMasterState
        CMP      r0,#2
        BEQ      |L1.4|
        LDR      r0,|L1.1024|
        LDR      r0,[r0,#0]  ; I2CMasterState
        CMP      r0,#1
        BEQ      |L1.4|
        MOV      r0,#2
        LDR      r3,|L1.1024|
        STR      r0,[r3,#0]  ; I2CMasterState
        MOV      r0,#3
        LDR      r3,|L1.1028|
        STR      r0,[r3,#0]  ; I2CWriteLength
        MOV      r0,#0
        LDR      r3,|L1.1032|
        STR      r0,[r3,#0]  ; I2CReadLength
        MOV      r0,#0x42
        LDR      r3,|L1.1036|
        STRB     r0,[r3,#0]
        MOV      r0,r3
        STRB     r2,[r0,#1]
        STRB     r1,[r0,#2]
        MOV      r0,#1
        LDR      r3,|L1.1040|
        STRB     r0,[r3,#0]
        MOV      r0,#4
        LDR      r3,|L1.1044|
        STR      r0,[r3,#0x18]
        MOV      r0,r3
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x20
        STR      r0,[r3,#0]
        MOV      r0,#0
        BX       lr
        ENDP

ov7670_read PROC
        MOV      r1,r0
        NOP      
|L1.94|
        LDR      r0,|L1.1024|
        LDR      r0,[r0,#0]  ; I2CMasterState
        CMP      r0,#2
        BEQ      |L1.94|
        LDR      r0,|L1.1024|
        LDR      r0,[r0,#0]  ; I2CMasterState
        CMP      r0,#1
        BEQ      |L1.94|
        MOV      r0,#2
        LDR      r2,|L1.1024|
        STR      r0,[r2,#0]  ; I2CMasterState
        LDR      r2,|L1.1028|
        STR      r0,[r2,#0]  ; I2CWriteLength
        MOV      r0,#0
        LDR      r2,|L1.1032|
        STR      r0,[r2,#0]  ; I2CReadLength
        MOV      r0,#0x42
        LDR      r2,|L1.1036|
        STRB     r0,[r2,#0]
        MOV      r0,r2
        STRB     r1,[r0,#1]
        MOV      r0,#0x43
        STRB     r0,[r2,#2]
        MOV      r0,#1
        LDR      r2,|L1.1040|
        STRB     r0,[r2,#0]
        MOV      r0,#4
        LDR      r2,|L1.1044|
        STR      r0,[r2,#0x18]
        MOV      r0,r2
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x20
        STR      r0,[r2,#0]
        NOP      
|L1.176|
        LDR      r0,|L1.1024|
        LDR      r0,[r0,#0]  ; I2CMasterState
        CMP      r0,#2
        BEQ      |L1.176|
        LDR      r0,|L1.1024|
        LDR      r0,[r0,#0]  ; I2CMasterState
        CMP      r0,#1
        BEQ      |L1.176|
        MOV      r0,#2
        LDR      r2,|L1.1024|
        STR      r0,[r2,#0]  ; I2CMasterState
        MOV      r0,#1
        LDR      r2,|L1.1028|
        STR      r0,[r2,#0]  ; I2CWriteLength
        LDR      r2,|L1.1032|
        STR      r0,[r2,#0]  ; I2CReadLength
        MOV      r0,#0x43
        LDR      r2,|L1.1036|
        STRB     r0,[r2,#0]
        MOV      r0,#1
        LDR      r2,|L1.1040|
        STRB     r0,[r2,#0]
        MOV      r0,#4
        LDR      r2,|L1.1044|
        STR      r0,[r2,#0x18]
        MOV      r0,r2
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x20
        STR      r0,[r2,#0]
        NOP      
|L1.248|
        LDR      r0,|L1.1024|
        LDR      r0,[r0,#0]  ; I2CMasterState
        CMP      r0,#2
        BEQ      |L1.248|
        LDR      r0,|L1.1024|
        LDR      r0,[r0,#0]  ; I2CMasterState
        CMP      r0,#1
        BEQ      |L1.248|
        MOVS     r0,#0
        BX       lr
        ENDP

Init_OV7670 PROC
        PUSH     {r4,lr}
        BL       Init_I2C0
        LDR      r0,|L1.1048|
        LDR      r0,[r0,#4]
        BIC      r0,r0,#0xc0000
        LDR      r1,|L1.1048|
        STR      r0,[r1,#4]
        LDR      r0,|L1.1052|
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0x2000000
        LDR      r1,|L1.1052|
        STR      r0,[r1,#0]
        LDR      r0,|L1.1056|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x2000000
        LDR      r1,|L1.1060|
        STR      r0,[r1,#0x94]
        MOV      r0,#0x15
        MOV      r1,#6
        CMP      r0,#0
        BGE      |L1.346|
        LSL      r2,r1,#27
        LSR      r4,r2,#24
        LDR      r2,|L1.1064|
        AND      r3,r0,#0xf
        SUB      r3,r3,#4
        STRB     r4,[r2,r3]
        B        |L1.358|
|L1.346|
        LSL      r2,r1,#27
        LSR      r3,r2,#24
        LDR      r2,|L1.1068|
        STRB     r3,[r2,r0]
|L1.358|
        NOP      
        MOV      r0,#0x15
        MOV      r1,#1
        LSL      r1,r1,r0
        LSR      r2,r0,#5
        MOV      r3,#0xe000e000
        ADD      r2,r3,r2,LSL #2
        STR      r1,[r2,#0x100]
        NOP      
        LDR      r0,|L1.1048|
        LDR      r0,[r0,#4]
        BIC      r0,r0,#0xc000000
        LDR      r1,|L1.1048|
        STR      r0,[r1,#4]
        LDR      r0,|L1.1052|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x20000000
        LDR      r1,|L1.1052|
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x10]
        LDR      r0,|L1.1048|
        LDR      r0,[r0,#4]
        BIC      r0,r0,#0x30000000
        LDR      r1,|L1.1048|
        STR      r0,[r1,#4]
        LDR      r0,|L1.1052|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x40000000
        LDR      r1,|L1.1052|
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x40000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        ORR      r0,r0,#0x40000000
        STR      r0,[r1,#0x10]
        LDR      r0,|L1.1048|
        LDR      r0,[r0,#4]
        BIC      r0,r0,#0x30000
        LDR      r1,|L1.1048|
        STR      r0,[r1,#4]
        LDR      r0,|L1.1052|
        LDR      r0,[r0,#0]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.1052|
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r0,|L1.1048|
        LDR      r0,[r0,#0xc]
        BIC      r0,r0,#0x30
        LDR      r1,|L1.1048|
        STR      r0,[r1,#0xc]
        MOV      r0,r1
        LDR      r0,[r0,#0xc]
        BIC      r0,r0,#0xc0
        STR      r0,[r1,#0xc]
        MOV      r0,r1
        LDR      r0,[r0,#0xc]
        BIC      r0,r0,#0x300
        STR      r0,[r1,#0xc]
        MOV      r0,r1
        LDR      r0,[r0,#0xc]
        BIC      r0,r0,#0xc00
        STR      r0,[r1,#0xc]
        MOV      r0,r1
        LDR      r0,[r0,#0xc]
        BIC      r0,r0,#0x3000
        STR      r0,[r1,#0xc]
        MOV      r0,r1
        LDR      r0,[r0,#0xc]
        BIC      r0,r0,#0xc000
        STR      r0,[r1,#0xc]
        MOV      r0,r1
        LDR      r0,[r0,#0xc]
        BIC      r0,r0,#0x30000
        STR      r0,[r1,#0xc]
        MOV      r0,r1
        LDR      r0,[r0,#0xc]
        BIC      r0,r0,#0xc0000
        STR      r0,[r1,#0xc]
        LDR      r0,|L1.1052|
        LDR      r0,[r0,#0x20]
        BIC      r0,r0,#0x40000
        LDR      r1,|L1.1052|
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        BIC      r0,r0,#0x80000
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        BIC      r0,r0,#0x100000
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        BIC      r0,r0,#0x200000
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        BIC      r0,r0,#0x400000
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        BIC      r0,r0,#0x800000
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        BIC      r0,r0,#0x1000000
        STR      r0,[r1,#0x20]
        MOV      r0,r1
        LDR      r0,[r0,#0x20]
        BIC      r0,r0,#0x2000000
        STR      r0,[r1,#0x20]
        MOV      r1,#4
        MOV      r0,#0x3a
        BL       ov7670_set
        MOVS     r1,#0x90
        MOVS     r0,#0x40
        BL       ov7670_set
        MOVS     r1,#4
        MOVS     r0,#0x12
        BL       ov7670_set
        MOVS     r1,#0x80
        MOVS     r0,#0x32
        BL       ov7670_set
        MOVS     r1,#0x16
        MOVS     r0,#0x17
        BL       ov7670_set
        MOVS     r1,#4
        MOVS     r0,#0x18
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#3
        BL       ov7670_set
        MOVS     r1,#3
        MOVS     r0,#0x19
        BL       ov7670_set
        MOVS     r1,#0x7b
        MOVS     r0,#0x1a
        BL       ov7670_set
        MOVS     r1,#1
        MOVS     r0,#0x11
        BL       ov7670_set
        MOVS     r1,#0x4a
        MOVS     r0,#0x6b
        BL       ov7670_set
        MOVS     r1,#0xc
        MOV      r0,r1
        BL       ov7670_set
        MOVS     r1,#0x19
        MOVS     r0,#0x3e
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x70
        BL       ov7670_set
        MOVS     r1,#1
        MOVS     r0,#0x71
        BL       ov7670_set
        MOVS     r1,#0x11
        MOVS     r0,#0x72
        BL       ov7670_set
        MOVS     r1,#0xf1
        MOVS     r0,#0x73
        BL       ov7670_set
        MOVS     r1,#2
        MOVS     r0,#0xa2
        BL       ov7670_set
        MOVS     r1,#0x20
        MOVS     r0,#0x7a
        BL       ov7670_set
        MOVS     r1,#0x1c
        MOVS     r0,#0x7b
        BL       ov7670_set
        MOVS     r1,#0x28
        MOVS     r0,#0x7c
        BL       ov7670_set
        MOVS     r1,#0x3c
        MOVS     r0,#0x7d
        BL       ov7670_set
        MOVS     r1,#0x55
        MOVS     r0,#0x7e
        BL       ov7670_set
        MOVS     r1,#0x68
        MOVS     r0,#0x7f
        BL       ov7670_set
        MOVS     r1,#0x76
        MOVS     r0,#0x80
        BL       ov7670_set
        MOVS     r1,#0x80
        MOVS     r0,#0x81
        BL       ov7670_set
        MOVS     r1,#0x88
        MOVS     r0,#0x82
        BL       ov7670_set
        MOVS     r1,#0x8f
        MOVS     r0,#0x83
        BL       ov7670_set
        MOVS     r1,#0x96
        MOVS     r0,#0x84
        BL       ov7670_set
        MOVS     r1,#0xa3
        MOVS     r0,#0x85
        BL       ov7670_set
        MOVS     r1,#0xaf
        MOVS     r0,#0x86
        BL       ov7670_set
        MOVS     r1,#0xc4
        MOVS     r0,#0x87
        BL       ov7670_set
        MOVS     r1,#0xd7
        MOVS     r0,#0x88
        BL       ov7670_set
        MOVS     r1,#0xe8
        MOVS     r0,#0x89
        BL       ov7670_set
        MOVS     r1,#0xe0
        MOVS     r0,#0x13
        BL       ov7670_set
        MOVS     r1,#0
        MOV      r0,r1
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x10
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0xd
        BL       ov7670_set
        MOVS     r1,#0x20
        MOVS     r0,#0x14
        BL       ov7670_set
        MOVS     r1,#5
        MOVS     r0,#0xa5
        BL       ov7670_set
        MOVS     r1,#7
        MOVS     r0,#0xab
        BL       ov7670_set
        MOVS     r1,#0x75
        MOVS     r0,#0x24
        BL       ov7670_set
        MOVS     r1,#0x63
        MOVS     r0,#0x25
        B        |L1.1072|
        DCW      0x0000
|L1.1024|
        DCD      I2CMasterState
|L1.1028|
        DCD      I2CWriteLength
|L1.1032|
        DCD      I2CReadLength
|L1.1036|
        DCD      I2CMasterBuffer
|L1.1040|
        DCD      I2C_mode
|L1.1044|
        DCD      0x4001c000
|L1.1048|
        DCD      0x4002c000
|L1.1052|
        DCD      0x2009c000
|L1.1056|
        DCD      0x40028094
|L1.1060|
        DCD      0x40028000
|L1.1064|
        DCD      0xe000ed18
|L1.1068|
        DCD      0xe000e400
|L1.1072|
        BL       ov7670_set
        MOVS     r1,#0xa5
        MOVS     r0,#0x26
        BL       ov7670_set
        MOVS     r1,#0x78
        MOVS     r0,#0x9f
        BL       ov7670_set
        MOVS     r1,#0x68
        MOVS     r0,#0xa0
        BL       ov7670_set
        MOVS     r1,#3
        MOVS     r0,#0xa1
        BL       ov7670_set
        MOVS     r1,#0xdf
        MOVS     r0,#0xa6
        BL       ov7670_set
        MOVS     r1,#0xdf
        MOVS     r0,#0xa7
        BL       ov7670_set
        MOVS     r1,#0xf0
        MOVS     r0,#0xa8
        BL       ov7670_set
        MOVS     r1,#0x90
        MOVS     r0,#0xa9
        BL       ov7670_set
        MOVS     r1,#0x94
        MOVS     r0,#0xaa
        BL       ov7670_set
        MOVS     r1,#0xe5
        MOVS     r0,#0x13
        BL       ov7670_set
        MOVS     r1,#0x61
        MOVS     r0,#0xe
        BL       ov7670_set
        MOVS     r1,#0x4b
        MOVS     r0,#0xf
        BL       ov7670_set
        MOVS     r1,#2
        MOVS     r0,#0x16
        BL       ov7670_set
        MOVS     r1,#0x37
        MOVS     r0,#0x1e
        BL       ov7670_set
        MOVS     r1,#2
        MOVS     r0,#0x21
        BL       ov7670_set
        MOVS     r1,#0x91
        MOVS     r0,#0x22
        BL       ov7670_set
        MOVS     r1,#7
        MOVS     r0,#0x29
        BL       ov7670_set
        MOVS     r1,#0xb
        MOVS     r0,#0x33
        BL       ov7670_set
        MOVS     r1,#0xb
        MOVS     r0,#0x35
        BL       ov7670_set
        MOVS     r1,#0x1d
        MOVS     r0,#0x37
        BL       ov7670_set
        MOVS     r1,#0x71
        MOVS     r0,#0x38
        BL       ov7670_set
        MOVS     r1,#0x2a
        MOVS     r0,#0x39
        BL       ov7670_set
        MOVS     r1,#0x78
        MOVS     r0,#0x3c
        BL       ov7670_set
        MOVS     r1,#0x40
        MOVS     r0,#0x4d
        BL       ov7670_set
        MOVS     r1,#0x20
        MOVS     r0,#0x4e
        BL       ov7670_set
        MOVS     r1,#0x5d
        MOVS     r0,#0x69
        BL       ov7670_set
        MOVS     r1,#0x19
        MOVS     r0,#0x74
        BL       ov7670_set
        MOVS     r1,#0x4f
        MOVS     r0,#0x8d
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x8e
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x8f
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x90
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x91
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x92
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x96
        BL       ov7670_set
        MOVS     r1,#0x80
        MOVS     r0,#0x9a
        BL       ov7670_set
        MOVS     r1,#0x84
        MOVS     r0,#0xb0
        BL       ov7670_set
        MOVS     r1,#0xc
        MOVS     r0,#0xb1
        BL       ov7670_set
        MOVS     r1,#0xe
        MOVS     r0,#0xb2
        BL       ov7670_set
        MOVS     r1,#0x82
        MOVS     r0,#0xb3
        BL       ov7670_set
        MOVS     r1,#0xa
        MOVS     r0,#0xb8
        BL       ov7670_set
        MOVS     r1,#4
        MOVS     r0,#0x64
        BL       ov7670_set
        MOVS     r1,#0x20
        MOVS     r0,#0x65
        BL       ov7670_set
        MOVS     r1,#5
        MOVS     r0,#0x66
        BL       ov7670_set
        MOVS     r1,#4
        MOVS     r0,#0x94
        BL       ov7670_set
        MOVS     r1,#8
        MOVS     r0,#0x95
        BL       ov7670_set
        MOVS     r1,#0xa
        MOVS     r0,#0x6c
        BL       ov7670_set
        MOVS     r1,#0x55
        MOVS     r0,#0x6d
        BL       ov7670_set
        MOVS     r1,#0x80
        MOVS     r0,#0x4f
        BL       ov7670_set
        MOVS     r1,#0x80
        MOVS     r0,#0x50
        BL       ov7670_set
        MOVS     r1,#0
        MOVS     r0,#0x51
        BL       ov7670_set
        MOVS     r1,#0x22
        MOVS     r0,#0x52
        BL       ov7670_set
        MOVS     r1,#0x5e
        MOVS     r0,#0x53
        BL       ov7670_set
        MOVS     r1,#0x80
        MOVS     r0,#0x54
        BL       ov7670_set
        MOVS     r1,#2
        MOVS     r0,#0x15
        BL       ov7670_set
        MOVS     r0,#1
        BL       OV7670_AWBmode
        BL       getOV7670_RGBgain
        BL       getOV7670_BriConLum
        MOVS     r0,#0x14
        BL       OV7670_FPS
        MOVS     r0,#1
        BL       OV7670_mirror
        POP      {r4,pc}
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "OV7670\\OV7670.c"
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___8_OV7670_c_36012b71____REV16|
#line 114 "C:\\Keil\\ARM\\CMSIS\\Include\\core_cmInstr.h"
|__asm___8_OV7670_c_36012b71____REV16| PROC
#line 115

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___8_OV7670_c_36012b71____REVSH|
#line 128
|__asm___8_OV7670_c_36012b71____REVSH| PROC
#line 129

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT ov7670_set [CODE]
        EXPORT ov7670_read [CODE]
        EXPORT Init_OV7670 [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT I2CMasterState [DATA]
        IMPORT I2CWriteLength [DATA]
        IMPORT I2CReadLength [DATA]
        IMPORT I2CMasterBuffer [DATA]
        IMPORT I2C_mode [DATA]
        IMPORT Init_I2C0 [CODE]
        IMPORT OV7670_AWBmode [CODE]
        IMPORT getOV7670_RGBgain [CODE]
        IMPORT getOV7670_BriConLum [CODE]
        IMPORT OV7670_FPS [CODE]
        IMPORT OV7670_mirror [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
