; generated by ARM C/C++ Compiler, 4.1 [Build 791]
; commandline ArmCC [--debug -c --asm -oov7670_detect_games.o --depend=ov7670_detect_games.d --cpu=Cortex-M3 --apcs=interwork -O0 -IC:\Keil\ARM\CMSIS\Include -IC:\Keil\ARM\INC\NXP\LPC17xx --omf_browse=ov7670_detect_games.crf GAMES\OV7670_detect_games.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

masscentre_detect_players PROC
        PUSH     {r4,lr}
        MOV      r2,#0
        MOV      r3,r2
        LDR      r4,|L1.1028|
        STR      r3,[r4,#0]  ; total_mass
        MOV      r0,r2
        B        |L1.72|
|L1.16|
        MOV      r1,#1
        B        |L1.62|
|L1.22|
        LDR      r3,|L1.1032|
        ADD      r3,r3,r0,LSL #5
        LDRH     r3,[r3,r1,LSL #1]
        MLA      r2,r3,r0,r2
        LDR      r3,|L1.1032|
        ADD      r3,r3,r0,LSL #5
        LDRH     r3,[r3,r1,LSL #1]
        LDR      r4,|L1.1028|
        LDR      r4,[r4,#0]  ; total_mass
        ADD      r3,r3,r4
        LDR      r4,|L1.1028|
        STR      r3,[r4,#0]  ; total_mass
        ADD      r3,r1,#1
        UXTH     r1,r3
|L1.62|
        CMP      r1,#6
        BLT      |L1.22|
        ADD      r3,r0,#1
        UXTH     r0,r3
|L1.72|
        CMP      r0,#0xc
        BLT      |L1.16|
        ADD      r3,r2,r2,LSL #2
        LSL      r3,r3,#6
        LSR      r3,r3,#4
        LDR      r4,|L1.1028|
        LDR      r4,[r4,#0]  ; total_mass
        UDIV     r3,r3,r4
        LDR      r4,|L1.1036|
        STRH     r3,[r4,#0]
        MOV      r2,#0
        MOV      r3,r2
        LDR      r4,|L1.1028|
        STR      r3,[r4,#0]  ; total_mass
        MOV      r0,r2
        B        |L1.170|
|L1.114|
        MOV      r1,#0xa
        B        |L1.160|
|L1.120|
        LDR      r3,|L1.1032|
        ADD      r3,r3,r0,LSL #5
        LDRH     r3,[r3,r1,LSL #1]
        MLA      r2,r3,r0,r2
        LDR      r3,|L1.1032|
        ADD      r3,r3,r0,LSL #5
        LDRH     r3,[r3,r1,LSL #1]
        LDR      r4,|L1.1028|
        LDR      r4,[r4,#0]  ; total_mass
        ADD      r3,r3,r4
        LDR      r4,|L1.1028|
        STR      r3,[r4,#0]  ; total_mass
        ADD      r3,r1,#1
        UXTH     r1,r3
|L1.160|
        CMP      r1,#0xf
        BLT      |L1.120|
        ADD      r3,r0,#1
        UXTH     r0,r3
|L1.170|
        CMP      r0,#0xc
        BLT      |L1.114|
        ADD      r3,r2,r2,LSL #2
        LSL      r3,r3,#6
        LSR      r3,r3,#4
        LDR      r4,|L1.1028|
        LDR      r4,[r4,#0]  ; total_mass
        UDIV     r3,r3,r4
        LDR      r4,|L1.1040|
        STRH     r3,[r4,#0]
        POP      {r4,pc}
        ENDP

Detect_for_games PROC
        PUSH     {r4-r10,lr}
        MOV      r7,r0
        MOV      r4,#0
        MOV      r3,#0xef
        MOV      r2,#0x13f
        MOV      r1,#0
        MOV      r0,r1
        BL       Window
        MOVS     r1,#0
        MOV      r0,r1
        BL       LCD_SetCursor
        LDR      r0,|L1.1044|
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x20000000
        LDR      r1,|L1.1044|
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x40000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x1000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        ORR      r0,r0,#0x40000000
        STR      r0,[r1,#0x10]
        LDR      r0,|L1.1048|
        LDR      r0,[r0,#0]  ; fps_aux
        ADD      r0,r0,#1
        LDR      r1,|L1.1048|
        STR      r0,[r1,#0]  ; fps_aux
        MOV      r8,r4
        B        |L1.406|
|L1.374|
        MOV      r5,#0
        B        |L1.398|
|L1.380|
        MOV      r0,#0
        LDR      r1,|L1.1032|
        ADD      r1,r1,r8,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        ADD      r5,r5,#1
|L1.398|
        CMP      r5,#0x10
        BCC      |L1.380|
        ADD      r8,r8,#1
|L1.406|
        CMP      r8,#0xc
        BCC      |L1.374|
        MOV      r6,#0
        B.W      |L1.5214|
|L1.420|
        MOV      r9,#0
        B.W      |L1.5202|
|L1.428|
        MOV      r5,#0
        B.W      |L1.5192|
|L1.436|
        RSB      r1,r5,#0xf
        MOV      r0,#1
        LSL      r0,r0,r1
        LDR      r1,|L1.1052|
        LDRH     r1,[r1,#0]  ; detect_width_zone
        TST      r0,r1
        BEQ      |L1.708|
        LDR      r0,|L1.1044|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.1044|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.1056|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.536|
        MOV      r3,r2
        B        |L1.538|
|L1.536|
        RSBS     r3,r2,#0
|L1.538|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.646|
        LDR      r3,|L1.1064|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.568|
        MOV      r3,r1
        B        |L1.570|
|L1.568|
        RSBS     r3,r1,#0
|L1.570|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.646|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.1068|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.608|
        MOV      r3,r0
        B        |L1.610|
|L1.608|
        RSBS     r3,r0,#0
|L1.610|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.646|
        LDR      r0,|L1.1032|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.1032|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.646|
        LDR      r0,|L1.1044|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.1044|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        B        |L1.710|
|L1.708|
        B        |L1.2734|
|L1.710|
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.1056|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.730|
        MOV      r3,r2
        B        |L1.732|
|L1.730|
        RSBS     r3,r2,#0
|L1.732|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.840|
        LDR      r3,|L1.1064|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.762|
        MOV      r3,r1
        B        |L1.764|
|L1.762|
        RSBS     r3,r1,#0
|L1.764|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.840|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.1068|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.802|
        MOV      r3,r0
        B        |L1.804|
|L1.802|
        RSBS     r3,r0,#0
|L1.804|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.840|
        LDR      r0,|L1.1032|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.1032|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.840|
        LDR      r0,|L1.1044|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.1044|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.1056|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.920|
        MOV      r3,r2
        B        |L1.922|
|L1.920|
        RSBS     r3,r2,#0
|L1.922|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1076|
        LDR      r3,|L1.1064|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.952|
        MOV      r3,r1
        B        |L1.954|
|L1.952|
        RSBS     r3,r1,#0
|L1.954|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1076|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.1068|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.992|
        MOV      r3,r0
        B        |L1.994|
|L1.992|
        RSBS     r3,r0,#0
|L1.994|
        LDR      r12,|L1.1060|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1076|
        LDR      r0,|L1.1032|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.1032|
        ADD      r1,r1,r6,LSL #5
        B        |L1.1072|
|L1.1028|
        DCD      total_mass
|L1.1032|
        DCD      scn_zone
|L1.1036|
        DCD      player1_y
|L1.1040|
        DCD      player2_y
|L1.1044|
        DCD      0x2009c000
|L1.1048|
        DCD      fps_aux
|L1.1052|
        DCD      detect_width_zone
|L1.1056|
        DCD      cd_R
|L1.1060|
        DCD      umbral
|L1.1064|
        DCD      cd_G
|L1.1068|
        DCD      cd_B
|L1.1072|
        STRH     r0,[r1,r5,LSL #1]
|L1.1076|
        LDR      r0,|L1.2096|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.2096|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.2100|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1156|
        MOV      r3,r2
        B        |L1.1158|
|L1.1156|
        RSBS     r3,r2,#0
|L1.1158|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1266|
        LDR      r3,|L1.2108|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1188|
        MOV      r3,r1
        B        |L1.1190|
|L1.1188|
        RSBS     r3,r1,#0
|L1.1190|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1266|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2112|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1228|
        MOV      r3,r0
        B        |L1.1230|
|L1.1228|
        RSBS     r3,r0,#0
|L1.1230|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1266|
        LDR      r0,|L1.2116|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2116|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.1266|
        LDR      r0,|L1.2096|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.2096|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.2100|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1346|
        MOV      r3,r2
        B        |L1.1348|
|L1.1346|
        RSBS     r3,r2,#0
|L1.1348|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1456|
        LDR      r3,|L1.2108|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1378|
        MOV      r3,r1
        B        |L1.1380|
|L1.1378|
        RSBS     r3,r1,#0
|L1.1380|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1456|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2112|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1418|
        MOV      r3,r0
        B        |L1.1420|
|L1.1418|
        RSBS     r3,r0,#0
|L1.1420|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1456|
        LDR      r0,|L1.2116|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2116|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.1456|
        LDR      r0,|L1.2096|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.2096|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.2100|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1536|
        MOV      r3,r2
        B        |L1.1538|
|L1.1536|
        RSBS     r3,r2,#0
|L1.1538|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1646|
        LDR      r3,|L1.2108|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1568|
        MOV      r3,r1
        B        |L1.1570|
|L1.1568|
        RSBS     r3,r1,#0
|L1.1570|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1646|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2112|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1608|
        MOV      r3,r0
        B        |L1.1610|
|L1.1608|
        RSBS     r3,r0,#0
|L1.1610|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1646|
        LDR      r0,|L1.2116|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2116|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.1646|
        LDR      r0,|L1.2096|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.2096|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.2100|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1726|
        MOV      r3,r2
        B        |L1.1728|
|L1.1726|
        RSBS     r3,r2,#0
|L1.1728|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1836|
        LDR      r3,|L1.2108|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1758|
        MOV      r3,r1
        B        |L1.1760|
|L1.1758|
        RSBS     r3,r1,#0
|L1.1760|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1836|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2112|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1798|
        MOV      r3,r0
        B        |L1.1800|
|L1.1798|
        RSBS     r3,r0,#0
|L1.1800|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1836|
        LDR      r0,|L1.2116|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2116|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.1836|
        LDR      r0,|L1.2096|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.2096|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.2100|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1916|
        MOV      r3,r2
        B        |L1.1918|
|L1.1916|
        RSBS     r3,r2,#0
|L1.1918|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2026|
        LDR      r3,|L1.2108|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1948|
        MOV      r3,r1
        B        |L1.1950|
|L1.1948|
        RSBS     r3,r1,#0
|L1.1950|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2026|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2112|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1988|
        MOV      r3,r0
        B        |L1.1990|
|L1.1988|
        RSBS     r3,r0,#0
|L1.1990|
        LDR      r12,|L1.2104|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2026|
        LDR      r0,|L1.2116|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2116|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.2026|
        LDR      r0,|L1.2096|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.2096|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.2100|
        B        |L1.2120|
|L1.2096|
        DCD      0x2009c000
|L1.2100|
        DCD      cd_R
|L1.2104|
        DCD      umbral
|L1.2108|
        DCD      cd_G
|L1.2112|
        DCD      cd_B
|L1.2116|
        DCD      scn_zone
|L1.2120|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2132|
        MOV      r3,r2
        B        |L1.2134|
|L1.2132|
        RSBS     r3,r2,#0
|L1.2134|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2242|
        LDR      r3,|L1.3160|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2164|
        MOV      r3,r1
        B        |L1.2166|
|L1.2164|
        RSBS     r3,r1,#0
|L1.2166|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2242|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3164|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2204|
        MOV      r3,r0
        B        |L1.2206|
|L1.2204|
        RSBS     r3,r0,#0
|L1.2206|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2242|
        LDR      r0,|L1.3168|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3168|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.2242|
        LDR      r0,|L1.3172|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.3172|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.3176|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2322|
        MOV      r3,r2
        B        |L1.2324|
|L1.2322|
        RSBS     r3,r2,#0
|L1.2324|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2432|
        LDR      r3,|L1.3160|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2354|
        MOV      r3,r1
        B        |L1.2356|
|L1.2354|
        RSBS     r3,r1,#0
|L1.2356|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2432|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3164|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2394|
        MOV      r3,r0
        B        |L1.2396|
|L1.2394|
        RSBS     r3,r0,#0
|L1.2396|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2432|
        LDR      r0,|L1.3168|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3168|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.2432|
        LDR      r0,|L1.3172|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.3172|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.3176|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2512|
        MOV      r3,r2
        B        |L1.2514|
|L1.2512|
        RSBS     r3,r2,#0
|L1.2514|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2622|
        LDR      r3,|L1.3160|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2544|
        MOV      r3,r1
        B        |L1.2546|
|L1.2544|
        RSBS     r3,r1,#0
|L1.2546|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2622|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3164|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2584|
        MOV      r3,r0
        B        |L1.2586|
|L1.2584|
        RSBS     r3,r0,#0
|L1.2586|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2622|
        LDR      r0,|L1.3168|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3168|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.2622|
        LDR      r0,|L1.3172|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.3172|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.3176|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2702|
        MOV      r3,r2
        B        |L1.2704|
|L1.2702|
        RSBS     r3,r2,#0
|L1.2704|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2814|
        LDR      r3,|L1.3160|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2736|
        MOV      r3,r1
        B        |L1.2738|
|L1.2734|
        B        |L1.4386|
|L1.2736|
        RSBS     r3,r1,#0
|L1.2738|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2814|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3164|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2776|
        MOV      r3,r0
        B        |L1.2778|
|L1.2776|
        RSBS     r3,r0,#0
|L1.2778|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2814|
        LDR      r0,|L1.3168|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3168|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.2814|
        LDR      r0,|L1.3172|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.3172|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.3176|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2894|
        MOV      r3,r2
        B        |L1.2896|
|L1.2894|
        RSBS     r3,r2,#0
|L1.2896|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3004|
        LDR      r3,|L1.3160|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2926|
        MOV      r3,r1
        B        |L1.2928|
|L1.2926|
        RSBS     r3,r1,#0
|L1.2928|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3004|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3164|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2966|
        MOV      r3,r0
        B        |L1.2968|
|L1.2966|
        RSBS     r3,r0,#0
|L1.2968|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3004|
        LDR      r0,|L1.3168|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3168|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.3004|
        LDR      r0,|L1.3172|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.3172|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.3176|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3084|
        MOV      r3,r2
        B        |L1.3086|
|L1.3084|
        RSBS     r3,r2,#0
|L1.3086|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3218|
        LDR      r3,|L1.3160|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3116|
        MOV      r3,r1
        B        |L1.3118|
|L1.3116|
        RSBS     r3,r1,#0
|L1.3118|
        LDR      r12,|L1.3156|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3218|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3164|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3180|
        MOV      r3,r0
        B        |L1.3182|
|L1.3156|
        DCD      umbral
|L1.3160|
        DCD      cd_G
|L1.3164|
        DCD      cd_B
|L1.3168|
        DCD      scn_zone
|L1.3172|
        DCD      0x2009c000
|L1.3176|
        DCD      cd_R
|L1.3180|
        RSBS     r3,r0,#0
|L1.3182|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3218|
        LDR      r0,|L1.4212|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4212|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.3218|
        LDR      r0,|L1.4216|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.4216|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.4220|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3298|
        MOV      r3,r2
        B        |L1.3300|
|L1.3298|
        RSBS     r3,r2,#0
|L1.3300|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3408|
        LDR      r3,|L1.4224|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3330|
        MOV      r3,r1
        B        |L1.3332|
|L1.3330|
        RSBS     r3,r1,#0
|L1.3332|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3408|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4228|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3370|
        MOV      r3,r0
        B        |L1.3372|
|L1.3370|
        RSBS     r3,r0,#0
|L1.3372|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3408|
        LDR      r0,|L1.4212|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4212|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.3408|
        LDR      r0,|L1.4216|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.4216|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.4220|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3488|
        MOV      r3,r2
        B        |L1.3490|
|L1.3488|
        RSBS     r3,r2,#0
|L1.3490|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3598|
        LDR      r3,|L1.4224|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3520|
        MOV      r3,r1
        B        |L1.3522|
|L1.3520|
        RSBS     r3,r1,#0
|L1.3522|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3598|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4228|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3560|
        MOV      r3,r0
        B        |L1.3562|
|L1.3560|
        RSBS     r3,r0,#0
|L1.3562|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3598|
        LDR      r0,|L1.4212|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4212|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.3598|
        LDR      r0,|L1.4216|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.4216|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.4220|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3678|
        MOV      r3,r2
        B        |L1.3680|
|L1.3678|
        RSBS     r3,r2,#0
|L1.3680|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3788|
        LDR      r3,|L1.4224|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3710|
        MOV      r3,r1
        B        |L1.3712|
|L1.3710|
        RSBS     r3,r1,#0
|L1.3712|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3788|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4228|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3750|
        MOV      r3,r0
        B        |L1.3752|
|L1.3750|
        RSBS     r3,r0,#0
|L1.3752|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3788|
        LDR      r0,|L1.4212|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4212|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.3788|
        LDR      r0,|L1.4216|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.4216|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.4220|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3868|
        MOV      r3,r2
        B        |L1.3870|
|L1.3868|
        RSBS     r3,r2,#0
|L1.3870|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3978|
        LDR      r3,|L1.4224|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3900|
        MOV      r3,r1
        B        |L1.3902|
|L1.3900|
        RSBS     r3,r1,#0
|L1.3902|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3978|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4228|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3940|
        MOV      r3,r0
        B        |L1.3942|
|L1.3940|
        RSBS     r3,r0,#0
|L1.3942|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3978|
        LDR      r0,|L1.4212|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4212|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.3978|
        LDR      r0,|L1.4216|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.4216|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.4220|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.4058|
        MOV      r3,r2
        B        |L1.4060|
|L1.4058|
        RSBS     r3,r2,#0
|L1.4060|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4168|
        LDR      r3,|L1.4224|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.4090|
        MOV      r3,r1
        B        |L1.4092|
|L1.4090|
        RSBS     r3,r1,#0
|L1.4092|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.4168|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4228|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.4130|
        MOV      r3,r0
        B        |L1.4132|
|L1.4130|
        RSBS     r3,r0,#0
|L1.4132|
        LDR      r12,|L1.4208|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4168|
        LDR      r0,|L1.4212|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4212|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.4168|
        LDR      r0,|L1.4216|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.4216|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        B        |L1.4232|
|L1.4208|
        DCD      umbral
|L1.4212|
        DCD      scn_zone
|L1.4216|
        DCD      0x2009c000
|L1.4220|
        DCD      cd_R
|L1.4224|
        DCD      cd_G
|L1.4228|
        DCD      cd_B
|L1.4232|
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        LDR      r3,|L1.5264|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.4274|
        MOV      r3,r2
        B        |L1.4276|
|L1.4274|
        RSBS     r3,r2,#0
|L1.4276|
        LDR      r12,|L1.5268|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
|L1.4286|
        BGE      |L1.4384|
        LDR      r3,|L1.5272|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.4306|
        MOV      r3,r1
        B        |L1.4308|
|L1.4306|
        RSBS     r3,r1,#0
|L1.4308|
        LDR      r12,|L1.5268|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.4286|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.5276|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.4346|
        MOV      r3,r0
        B        |L1.4348|
|L1.4346|
        RSBS     r3,r0,#0
|L1.4348|
        LDR      r12,|L1.5268|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4286|
        LDR      r0,|L1.5280|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.5280|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
|L1.4384|
        B        |L1.5188|
|L1.4386|
        LDR      r0,|L1.5284|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.5284|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
|L1.5188|
        ADD      r5,r5,#1
|L1.5192|
        CMP      r5,#0x10
        BCC      |L1.436|
        ADD      r9,r9,#1
|L1.5202|
        CMP      r9,#0x14
        BCC      |L1.428|
        ADD      r6,r6,#1
|L1.5214|
        CMP      r6,#0xc
        BCC      |L1.420|
        CBNZ     r7,|L1.5228|
        BL       masscentre_detect_players
        B        |L1.5236|
|L1.5228|
        CMP      r7,#1
        BNE      |L1.5236|
        BL       masscentre_detect
|L1.5236|
        LDR      r0,|L1.5288|
        LDRH     r0,[r0,#0]  ; color_detect
        UBFX     r0,r0,#5,#6
        LDR      r1,|L1.5272|
        STRB     r0,[r1,#0]
        LDR      r0,|L1.5288|
        LDRH     r0,[r0,#0]  ; color_detect
        AND      r0,r0,#0x1f
        LDR      r1,|L1.5276|
        STRB     r0,[r1,#0]
        POP      {r4-r10,pc}
|L1.5264|
        DCD      cd_R
|L1.5268|
        DCD      umbral
|L1.5272|
        DCD      cd_G
|L1.5276|
        DCD      cd_B
|L1.5280|
        DCD      scn_zone
|L1.5284|
        DCD      0x2009c000
|L1.5288|
        DCD      color_detect
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=1

detect_width_zone
        DCW      0x7c3e
player1_y
        DCB      0x00,0x00
player2_y
        DCB      0x00,0x00

;*** Start embedded assembler ***

#line 1 "GAMES\\OV7670_detect_games.c"
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___21_OV7670_detect_games_c_06ef93ce____REV16|
#line 114 "C:\\Keil\\ARM\\CMSIS\\Include\\core_cmInstr.h"
|__asm___21_OV7670_detect_games_c_06ef93ce____REV16| PROC
#line 115

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___21_OV7670_detect_games_c_06ef93ce____REVSH|
#line 128
|__asm___21_OV7670_detect_games_c_06ef93ce____REVSH| PROC
#line 129

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT masscentre_detect_players [CODE]
        EXPORT Detect_for_games [CODE]
        EXPORT detect_width_zone [DATA,SIZE=2]
        EXPORT player1_y [DATA,SIZE=2]
        EXPORT player2_y [DATA,SIZE=2]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT total_mass [DATA]
        IMPORT scn_zone [DATA]
        IMPORT Window [CODE]
        IMPORT LCD_SetCursor [CODE]
        IMPORT masscentre_detect [CODE]
        IMPORT fps_aux [DATA]
        IMPORT cd_R [DATA]
        IMPORT umbral [DATA]
        IMPORT cd_G [DATA]
        IMPORT cd_B [DATA]
        IMPORT color_detect [DATA]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
