; generated by ARM C/C++ Compiler, 4.1 [Build 791]
; commandline ArmCC [--debug -c --asm -oov7670_detect.o --depend=ov7670_detect.d --cpu=Cortex-M3 --apcs=interwork -O0 -IC:\Keil\ARM\CMSIS\Include -IC:\Keil\ARM\INC\NXP\LPC17xx --omf_browse=ov7670_detect.crf OV7670\OV7670_detect.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

masscentre_detect PROC
        PUSH     {r4,r5,lr}
        MOV      r2,#0
        MOV      r3,r2
        MOV      r4,r2
        LDR      r5,|L1.1024|
        STR      r4,[r5,#0]  ; total_mass
        MOV      r0,r2
        B        |L1.88|
|L1.18|
        MOV      r1,#0
        B        |L1.78|
|L1.24|
        LDR      r4,|L1.1028|
        ADD      r4,r4,r0,LSL #5
        LDRH     r4,[r4,r1,LSL #1]
        MLA      r3,r4,r0,r3
        LDR      r4,|L1.1028|
        ADD      r4,r4,r0,LSL #5
        LDRH     r4,[r4,r1,LSL #1]
        MLA      r2,r4,r1,r2
        LDR      r4,|L1.1028|
        ADD      r4,r4,r0,LSL #5
        LDRH     r4,[r4,r1,LSL #1]
        LDR      r5,|L1.1024|
        LDR      r5,[r5,#0]  ; total_mass
        ADD      r4,r4,r5
        LDR      r5,|L1.1024|
        STR      r4,[r5,#0]  ; total_mass
        ADD      r4,r1,#1
        UXTH     r1,r4
|L1.78|
        CMP      r1,#0x10
        BLT      |L1.24|
        ADD      r4,r0,#1
        UXTH     r0,r4
|L1.88|
        CMP      r0,#0xc
        BLT      |L1.18|
        ADD      r4,r2,r2,LSL #2
        LSL      r4,r4,#6
        LSR      r4,r4,#4
        LDR      r5,|L1.1024|
        LDR      r5,[r5,#0]  ; total_mass
        UDIV     r4,r4,r5
        LDR      r5,|L1.1032|
        STR      r4,[r5,#0]  ; det_x
        RSB      r4,r3,r3,LSL #4
        LSL      r4,r4,#4
        MOV      r5,#0xc
        UDIV     r4,r4,r5
        LDR      r5,|L1.1024|
        LDR      r5,[r5,#0]  ; total_mass
        UDIV     r4,r4,r5
        LDR      r5,|L1.1036|
        STR      r4,[r5,#0]  ; det_y
        POP      {r4,r5,pc}
        ENDP

montwell_detect PROC
        PUSH     {r4-r9,lr}
        MOV      r1,#0
        B        |L1.298|
|L1.156|
        MOV      r0,#0
        B        |L1.286|
|L1.162|
        MOV      r3,#0
        B        |L1.274|
|L1.168|
        MOV      r2,#0
        B        |L1.262|
|L1.174|
        SUB      r12,r1,r3
        MUL      r12,r12,r12
        SUB      r8,r0,r2
        SUB      r9,r0,r2
        MLA      r12,r8,r9,r12
        LDR      r8,|L1.1040|
        LDRH     r8,[r8,#0]  ; const_block
        MUL      r12,r12,r8
        UXTH     r4,r12
        CBZ      r4,|L1.254|
        LDR      r12,|L1.1028|
        ADD      r12,r12,r1,LSL #5
        LDRH     r12,[r12,r0,LSL #1]
        SDIV     r12,r12,r4
        LDR      r8,|L1.1028|
        ADD      r8,r8,r3,LSL #5
        LDRH     r8,[r8,r2,LSL #1]
        ADD      r12,r12,r8
        LDR      r8,|L1.1028|
        ADD      r8,r8,r3,LSL #5
        STRH     r12,[r8,r2,LSL #1]
|L1.254|
        ADD      r12,r2,#1
        UXTH     r2,r12
|L1.262|
        CMP      r2,#0x10
        BLT      |L1.174|
        ADD      r12,r3,#1
        UXTH     r3,r12
|L1.274|
        CMP      r3,#0xc
        BLT      |L1.168|
        ADD      r12,r0,#1
        UXTH     r0,r12
|L1.286|
        CMP      r0,#0x10
        BLT      |L1.162|
        ADD      r12,r1,#1
        UXTH     r1,r12
|L1.298|
        CMP      r1,#0xc
        BLT      |L1.156|
        MOV      r7,#0
        MOV      r1,r7
        B        |L1.368|
|L1.310|
        MOV      r0,#0
        B        |L1.356|
|L1.316|
        LDR      r12,|L1.1028|
        ADD      r12,r12,r1,LSL #5
        LDRH     r12,[r12,r0,LSL #1]
        CMP      r12,r7
        BLE      |L1.348|
        LDR      r12,|L1.1028|
        ADD      r12,r12,r1,LSL #5
        LDRH     r7,[r12,r0,LSL #1]
        MOV      r5,r0
        MOV      r6,r1
|L1.348|
        ADD      r12,r0,#1
        UXTH     r0,r12
|L1.356|
        CMP      r0,#0x10
        BLT      |L1.316|
        ADD      r12,r1,#1
        UXTH     r1,r12
|L1.368|
        CMP      r1,#0xc
        BLT      |L1.310|
        RSB      r12,r6,r6,LSL #4
        LSL      r12,r12,#4
        MOV      r8,#0xc
        SDIV     r12,r12,r8
        LDR      r8,|L1.1036|
        STR      r12,[r8,#0]  ; det_y
        ADD      r8,r5,r5,LSL #2
        LSL      r12,r8,#6
        ASR      r8,r12,#31
        ADD      r8,r12,r8,LSR #28
        ASR      r8,r8,#4
        LDR      r9,|L1.1032|
        STR      r8,[r9,#0]  ; det_x
        POP      {r4-r9,pc}
        ENDP

detect_read_frame_RGB565 PROC
        PUSH     {r3-r9,lr}
        MOV      r7,r0
        MOV      r4,#0
        MOV      r3,#0xef
        MOV      r2,#0x13f
        MOV      r1,#0
        MOV      r0,r1
        BL       Window
        MOVS     r1,#0
        MOV      r0,r1
        BL       LCD_SetCursor
        LDR      r0,|L1.1044|
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x20000000
        LDR      r1,|L1.1044|
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x40000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x1000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        ORR      r0,r0,#0x40000000
        STR      r0,[r1,#0x10]
        LDR      r0,|L1.1048|
        LDR      r0,[r0,#0]  ; fps_aux
        ADD      r0,r0,#1
        LDR      r1,|L1.1048|
        STR      r0,[r1,#0]  ; fps_aux
        MOV      r8,r4
        B        |L1.634|
|L1.602|
        MOV      r5,#0
        B        |L1.626|
|L1.608|
        MOV      r0,#0
        LDR      r1,|L1.1028|
        ADD      r1,r1,r8,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        ADD      r5,r5,#1
|L1.626|
        CMP      r5,#0x10
        BCC      |L1.608|
        ADD      r8,r8,#1
|L1.634|
        CMP      r8,#0xc
        BCC      |L1.602|
        MOV      r6,#0
        B.W      |L1.4986|
|L1.648|
        MOV      r9,#0
        B.W      |L1.4974|
|L1.656|
        MOV      r5,#0
        B.W      |L1.4964|
|L1.664|
        LDR      r0,|L1.1044|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.1044|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,#0x100
        STR      r0,[r1,#0x5c]
        MOV      r0,#0x28000000
        STR      r0,[r1,#0x3c]
        MOV      r0,#0x22
        STR      r0,[r1,#0x54]
        MOV      r0,#0
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,#0x100
        STR      r0,[r1,#0x5c]
        LDR      r3,|L1.1052|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.772|
        MOV      r3,r2
        B        |L1.774|
|L1.772|
        RSBS     r3,r2,#0
|L1.774|
        LDR      r12,|L1.1056|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.886|
        LDR      r3,|L1.1060|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.804|
        MOV      r3,r1
        B        |L1.806|
|L1.804|
        RSBS     r3,r1,#0
|L1.806|
        LDR      r12,|L1.1056|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.886|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.1064|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.844|
        MOV      r3,r0
        B        |L1.846|
|L1.844|
        RSBS     r3,r0,#0
|L1.846|
        LDR      r12,|L1.1056|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.886|
        LDR      r0,|L1.1028|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.1028|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.886|
        MOV      r0,#0x100
        LDR      r1,|L1.1044|
        STR      r0,[r1,#0x5c]
        MOV      r0,#0x8000000
        STR      r0,[r1,#0x38]
        UXTB     r0,r4
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.1052|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.990|
        MOV      r3,r2
        B        |L1.992|
|L1.990|
        RSBS     r3,r2,#0
|L1.992|
        LDR      r12,|L1.1056|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1150|
        LDR      r3,|L1.1060|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1068|
        MOV      r3,r1
        B        |L1.1070|
        DCW      0x0000
|L1.1024|
        DCD      total_mass
|L1.1028|
        DCD      scn_zone
|L1.1032|
        DCD      det_x
|L1.1036|
        DCD      det_y
|L1.1040|
        DCD      const_block
|L1.1044|
        DCD      0x2009c000
|L1.1048|
        DCD      fps_aux
|L1.1052|
        DCD      cd_R
|L1.1056|
        DCD      umbral
|L1.1060|
        DCD      cd_G
|L1.1064|
        DCD      cd_B
|L1.1068|
        RSBS     r3,r1,#0
|L1.1070|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1150|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2136|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1108|
        MOV      r3,r0
        B        |L1.1110|
|L1.1108|
        RSBS     r3,r0,#0
|L1.1110|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1150|
        LDR      r0,|L1.2140|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2140|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.1150|
        UXTB     r0,r4
        LDR      r1,|L1.2144|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.2148|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1242|
        MOV      r3,r2
        B        |L1.1244|
|L1.1242|
        RSBS     r3,r2,#0
|L1.1244|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1356|
        LDR      r3,|L1.2152|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1274|
        MOV      r3,r1
        B        |L1.1276|
|L1.1274|
        RSBS     r3,r1,#0
|L1.1276|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1356|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2136|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1314|
        MOV      r3,r0
        B        |L1.1316|
|L1.1314|
        RSBS     r3,r0,#0
|L1.1316|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1356|
        LDR      r0,|L1.2140|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2140|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.1356|
        UXTB     r0,r4
        LDR      r1,|L1.2144|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.2148|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1448|
        MOV      r3,r2
        B        |L1.1450|
|L1.1448|
        RSBS     r3,r2,#0
|L1.1450|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1562|
        LDR      r3,|L1.2152|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1480|
        MOV      r3,r1
        B        |L1.1482|
|L1.1480|
        RSBS     r3,r1,#0
|L1.1482|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1562|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2136|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1520|
        MOV      r3,r0
        B        |L1.1522|
|L1.1520|
        RSBS     r3,r0,#0
|L1.1522|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1562|
        LDR      r0,|L1.2140|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2140|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.1562|
        UXTB     r0,r4
        LDR      r1,|L1.2144|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.2148|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1654|
        MOV      r3,r2
        B        |L1.1656|
|L1.1654|
        RSBS     r3,r2,#0
|L1.1656|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1768|
        LDR      r3,|L1.2152|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1686|
        MOV      r3,r1
        B        |L1.1688|
|L1.1686|
        RSBS     r3,r1,#0
|L1.1688|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1768|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2136|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1726|
        MOV      r3,r0
        B        |L1.1728|
|L1.1726|
        RSBS     r3,r0,#0
|L1.1728|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1768|
        LDR      r0,|L1.2140|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2140|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.1768|
        UXTB     r0,r4
        LDR      r1,|L1.2144|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.2148|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.1860|
        MOV      r3,r2
        B        |L1.1862|
|L1.1860|
        RSBS     r3,r2,#0
|L1.1862|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1974|
        LDR      r3,|L1.2152|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.1892|
        MOV      r3,r1
        B        |L1.1894|
|L1.1892|
        RSBS     r3,r1,#0
|L1.1894|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.1974|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2136|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.1932|
        MOV      r3,r0
        B        |L1.1934|
|L1.1932|
        RSBS     r3,r0,#0
|L1.1934|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.1974|
        LDR      r0,|L1.2140|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.2140|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.1974|
        UXTB     r0,r4
        LDR      r1,|L1.2144|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.2148|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2066|
        MOV      r3,r2
        B        |L1.2068|
|L1.2066|
        RSBS     r3,r2,#0
|L1.2068|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2208|
        LDR      r3,|L1.2152|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2098|
        MOV      r3,r1
        B        |L1.2100|
|L1.2098|
        RSBS     r3,r1,#0
|L1.2100|
        LDR      r12,|L1.2132|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2208|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.2136|
        LDRB     r12,[r12,#0]  ; cd_B
        B        |L1.2156|
        DCW      0x0000
|L1.2132|
        DCD      umbral
|L1.2136|
        DCD      cd_B
|L1.2140|
        DCD      scn_zone
|L1.2144|
        DCD      0x2009c000
|L1.2148|
        DCD      cd_R
|L1.2152|
        DCD      cd_G
|L1.2156|
        SUBS     r0,r12,r3
        BMI      |L1.2166|
        MOV      r3,r0
        B        |L1.2168|
|L1.2166|
        RSBS     r3,r0,#0
|L1.2168|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2208|
        LDR      r0,|L1.3200|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3200|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.2208|
        UXTB     r0,r4
        LDR      r1,|L1.3204|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.3208|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2300|
        MOV      r3,r2
        B        |L1.2302|
|L1.2300|
        RSBS     r3,r2,#0
|L1.2302|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2414|
        LDR      r3,|L1.3212|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2332|
        MOV      r3,r1
        B        |L1.2334|
|L1.2332|
        RSBS     r3,r1,#0
|L1.2334|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2414|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3216|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2372|
        MOV      r3,r0
        B        |L1.2374|
|L1.2372|
        RSBS     r3,r0,#0
|L1.2374|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2414|
        LDR      r0,|L1.3200|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3200|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.2414|
        UXTB     r0,r4
        LDR      r1,|L1.3204|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.3208|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2506|
        MOV      r3,r2
        B        |L1.2508|
|L1.2506|
        RSBS     r3,r2,#0
|L1.2508|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2620|
        LDR      r3,|L1.3212|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2538|
        MOV      r3,r1
        B        |L1.2540|
|L1.2538|
        RSBS     r3,r1,#0
|L1.2540|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2620|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3216|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2578|
        MOV      r3,r0
        B        |L1.2580|
|L1.2578|
        RSBS     r3,r0,#0
|L1.2580|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2620|
        LDR      r0,|L1.3200|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3200|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.2620|
        UXTB     r0,r4
        LDR      r1,|L1.3204|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.3208|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2712|
        MOV      r3,r2
        B        |L1.2714|
|L1.2712|
        RSBS     r3,r2,#0
|L1.2714|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2826|
        LDR      r3,|L1.3212|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2744|
        MOV      r3,r1
        B        |L1.2746|
|L1.2744|
        RSBS     r3,r1,#0
|L1.2746|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.2826|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3216|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2784|
        MOV      r3,r0
        B        |L1.2786|
|L1.2784|
        RSBS     r3,r0,#0
|L1.2786|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.2826|
        LDR      r0,|L1.3200|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3200|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.2826|
        UXTB     r0,r4
        LDR      r1,|L1.3204|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.3208|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.2918|
        MOV      r3,r2
        B        |L1.2920|
|L1.2918|
        RSBS     r3,r2,#0
|L1.2920|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3032|
        LDR      r3,|L1.3212|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.2950|
        MOV      r3,r1
        B        |L1.2952|
|L1.2950|
        RSBS     r3,r1,#0
|L1.2952|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3032|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3216|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.2990|
        MOV      r3,r0
        B        |L1.2992|
|L1.2990|
        RSBS     r3,r0,#0
|L1.2992|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3032|
        LDR      r0,|L1.3200|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.3200|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.3032|
        UXTB     r0,r4
        LDR      r1,|L1.3204|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.3208|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3124|
        MOV      r3,r2
        B        |L1.3126|
|L1.3124|
        RSBS     r3,r2,#0
|L1.3126|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3262|
        LDR      r3,|L1.3212|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3156|
        MOV      r3,r1
        B        |L1.3158|
|L1.3156|
        RSBS     r3,r1,#0
|L1.3158|
        LDR      r12,|L1.3196|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3262|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.3216|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3220|
        MOV      r3,r0
        B        |L1.3222|
|L1.3196|
        DCD      umbral
|L1.3200|
        DCD      scn_zone
|L1.3204|
        DCD      0x2009c000
|L1.3208|
        DCD      cd_R
|L1.3212|
        DCD      cd_G
|L1.3216|
        DCD      cd_B
|L1.3220|
        RSBS     r3,r0,#0
|L1.3222|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3262|
        LDR      r0,|L1.4252|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4252|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.3262|
        UXTB     r0,r4
        LDR      r1,|L1.4256|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.4260|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3354|
        MOV      r3,r2
        B        |L1.3356|
|L1.3354|
        RSBS     r3,r2,#0
|L1.3356|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3468|
        LDR      r3,|L1.4264|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3386|
        MOV      r3,r1
        B        |L1.3388|
|L1.3386|
        RSBS     r3,r1,#0
|L1.3388|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3468|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4268|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3426|
        MOV      r3,r0
        B        |L1.3428|
|L1.3426|
        RSBS     r3,r0,#0
|L1.3428|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3468|
        LDR      r0,|L1.4252|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4252|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.3468|
        UXTB     r0,r4
        LDR      r1,|L1.4256|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.4260|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3560|
        MOV      r3,r2
        B        |L1.3562|
|L1.3560|
        RSBS     r3,r2,#0
|L1.3562|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3674|
        LDR      r3,|L1.4264|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3592|
        MOV      r3,r1
        B        |L1.3594|
|L1.3592|
        RSBS     r3,r1,#0
|L1.3594|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3674|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4268|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3632|
        MOV      r3,r0
        B        |L1.3634|
|L1.3632|
        RSBS     r3,r0,#0
|L1.3634|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3674|
        LDR      r0,|L1.4252|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4252|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.3674|
        UXTB     r0,r4
        LDR      r1,|L1.4256|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.4260|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3766|
        MOV      r3,r2
        B        |L1.3768|
|L1.3766|
        RSBS     r3,r2,#0
|L1.3768|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3880|
        LDR      r3,|L1.4264|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.3798|
        MOV      r3,r1
        B        |L1.3800|
|L1.3798|
        RSBS     r3,r1,#0
|L1.3800|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.3880|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4268|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.3838|
        MOV      r3,r0
        B        |L1.3840|
|L1.3838|
        RSBS     r3,r0,#0
|L1.3840|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.3880|
        LDR      r0,|L1.4252|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4252|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.3880|
        UXTB     r0,r4
        LDR      r1,|L1.4256|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.4260|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.3972|
        MOV      r3,r2
        B        |L1.3974|
|L1.3972|
        RSBS     r3,r2,#0
|L1.3974|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4086|
        LDR      r3,|L1.4264|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.4004|
        MOV      r3,r1
        B        |L1.4006|
|L1.4004|
        RSBS     r3,r1,#0
|L1.4006|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.4086|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4268|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.4044|
        MOV      r3,r0
        B        |L1.4046|
|L1.4044|
        RSBS     r3,r0,#0
|L1.4046|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4086|
        LDR      r0,|L1.4252|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.4252|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.4086|
        UXTB     r0,r4
        LDR      r1,|L1.4256|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.4260|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.4178|
        MOV      r3,r2
        B        |L1.4180|
|L1.4178|
        RSBS     r3,r2,#0
|L1.4180|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4318|
        LDR      r3,|L1.4264|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.4210|
        MOV      r3,r1
        B        |L1.4212|
|L1.4210|
        RSBS     r3,r1,#0
|L1.4212|
        LDR      r12,|L1.4248|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.4318|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.4268|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.4276|
        B        |L1.4272|
|L1.4248|
        DCD      umbral
|L1.4252|
        DCD      scn_zone
|L1.4256|
        DCD      0x2009c000
|L1.4260|
        DCD      cd_R
|L1.4264|
        DCD      cd_G
|L1.4268|
        DCD      cd_B
|L1.4272|
        MOV      r3,r0
        B        |L1.4278|
|L1.4276|
        RSBS     r3,r0,#0
|L1.4278|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4318|
        LDR      r0,|L1.5176|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.5176|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.4318|
        UXTB     r0,r4
        LDR      r1,|L1.5180|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.5184|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.4410|
        MOV      r3,r2
        B        |L1.4412|
|L1.4410|
        RSBS     r3,r2,#0
|L1.4412|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4524|
        LDR      r3,|L1.5188|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.4442|
        MOV      r3,r1
        B        |L1.4444|
|L1.4442|
        RSBS     r3,r1,#0
|L1.4444|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.4524|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.5192|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.4482|
        MOV      r3,r0
        B        |L1.4484|
|L1.4482|
        RSBS     r3,r0,#0
|L1.4484|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4524|
        LDR      r0,|L1.5176|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.5176|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.4524|
        UXTB     r0,r4
        LDR      r1,|L1.5180|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.5184|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.4616|
        MOV      r3,r2
        B        |L1.4618|
|L1.4616|
        RSBS     r3,r2,#0
|L1.4618|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4730|
        LDR      r3,|L1.5188|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.4648|
        MOV      r3,r1
        B        |L1.4650|
|L1.4648|
        RSBS     r3,r1,#0
|L1.4650|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.4730|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.5192|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.4688|
        MOV      r3,r0
        B        |L1.4690|
|L1.4688|
        RSBS     r3,r0,#0
|L1.4690|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4730|
        LDR      r0,|L1.5176|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.5176|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.4730|
        UXTB     r0,r4
        LDR      r1,|L1.5180|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        LDR      r3,|L1.5184|
        LDRB     r3,[r3,#0]  ; cd_R
        SUBS     r2,r3,r4,LSR #11
        BMI      |L1.4822|
        MOV      r3,r2
        B        |L1.4824|
|L1.4822|
        RSBS     r3,r2,#0
|L1.4824|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4936|
        LDR      r3,|L1.5188|
        LDRB     r3,[r3,#0]  ; cd_G
        UBFX     r12,r4,#5,#6
        SUBS     r1,r3,r12
        BMI      |L1.4854|
        MOV      r3,r1
        B        |L1.4856|
|L1.4854|
        RSBS     r3,r1,#0
|L1.4856|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        LSL      r12,r12,#1
        CMP      r3,r12
        BGE      |L1.4936|
        AND      r3,r4,#0x1f
        LDR      r12,|L1.5192|
        LDRB     r12,[r12,#0]  ; cd_B
        SUBS     r0,r12,r3
        BMI      |L1.4894|
        MOV      r3,r0
        B        |L1.4896|
|L1.4894|
        RSBS     r3,r0,#0
|L1.4896|
        LDR      r12,|L1.5172|
        LDRB     r12,[r12,#0]  ; umbral
        CMP      r3,r12
        BGE      |L1.4936|
        LDR      r0,|L1.5176|
        ADD      r0,r0,r6,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        ADD      r0,r0,#1
        LDR      r1,|L1.5176|
        ADD      r1,r1,r6,LSL #5
        STRH     r0,[r1,r5,LSL #1]
        MOV      r4,#0xf800
|L1.4936|
        UXTB     r0,r4
        LDR      r1,|L1.5180|
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        ADD      r5,r5,#1
|L1.4964|
        CMP      r5,#0x10
        BCC      |L1.664|
        ADD      r9,r9,#1
|L1.4974|
        CMP      r9,#0x14
        BCC      |L1.656|
        ADD      r6,r6,#1
|L1.4986|
        CMP      r6,#0xc
        BCC      |L1.648|
        CBNZ     r7,|L1.5000|
        BL       montwell_detect
        B        |L1.5008|
|L1.5000|
        CMP      r7,#1
        BNE      |L1.5008|
        BL       masscentre_detect
|L1.5008|
        LDR      r0,|L1.5196|
        LDRH     r0,[r0,#0]  ; color_detect
        UBFX     r0,r0,#5,#6
        LDR      r1,|L1.5188|
        STRB     r0,[r1,#0]
        LDR      r0,|L1.5196|
        LDRH     r0,[r0,#0]  ; color_detect
        AND      r0,r0,#0x1f
        LDR      r1,|L1.5192|
        STRB     r0,[r1,#0]
        MOV      r0,#0
        MOV      r3,#0xffff
        ADR      r2,|L1.5200|
        STR      r0,[sp,#0]
        LDR      r0,|L1.5204|
        LDR      r0,[r0,#0]  ; det_y
        UXTH     r1,r0
        LDR      r0,|L1.5208|
        LDR      r0,[r0,#0]  ; det_x
        UXTH     r0,r0
        BL       GUI_Text
        POP      {r3-r9,pc}
        ENDP

show_blocks PROC
        PUSH     {r3-r7,lr}
        MOV      r4,#0
        B        |L1.5164|
|L1.5072|
        MOV      r5,#0
        B        |L1.5154|
|L1.5078|
        LDR      r0,|L1.5176|
        ADD      r0,r0,r4,LSL #5
        LDRH     r0,[r0,r5,LSL #1]
        MOVS     r1,#0xa
        SDIV     r6,r0,r1
        LDR      r1,|L1.5212|
        MOV      r0,r6
        BL       conversor_IaS
        RSB      r0,r4,r4,LSL #4
        LSLS     r0,r0,#4
        MOVS     r1,#0xc
        SDIV     r0,r0,r1
        UXTH     r7,r0
        MOV      r0,#0xffff
        ADD      r1,r5,r5,LSL #2
        LSLS     r6,r1,#6
        ASRS     r1,r6,#31
        ADD      r1,r6,r1,LSR #28
        STR      r0,[sp,#0]
        UBFX     r0,r1,#4,#16
        MOVS     r3,#0
        LDR      r2,|L1.5212|
        MOV      r1,r7
        BL       GUI_Text
        ADD      r0,r5,#1
        UXTH     r5,r0
|L1.5154|
        CMP      r5,#0x10
        BLT      |L1.5078|
        ADD      r0,r4,#1
        UXTH     r4,r0
|L1.5164|
        CMP      r4,#0xc
        BLT      |L1.5072|
        POP      {r3-r7,pc}
        ENDP

        DCW      0x0000
|L1.5172|
        DCD      umbral
|L1.5176|
        DCD      scn_zone
|L1.5180|
        DCD      0x2009c000
|L1.5184|
        DCD      cd_R
|L1.5188|
        DCD      cd_G
|L1.5192|
        DCD      cd_B
|L1.5196|
        DCD      color_detect
|L1.5200|
        DCB      "X",0
        DCB      0
        DCB      0
|L1.5204|
        DCD      det_y
|L1.5208|
        DCD      det_x
|L1.5212|
        DCD      delay_read

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "OV7670\\OV7670_detect.c"
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___15_OV7670_detect_c_cffdb185____REV16|
#line 114 "C:\\Keil\\ARM\\CMSIS\\Include\\core_cmInstr.h"
|__asm___15_OV7670_detect_c_cffdb185____REV16| PROC
#line 115

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___15_OV7670_detect_c_cffdb185____REVSH|
#line 128
|__asm___15_OV7670_detect_c_cffdb185____REVSH| PROC
#line 129

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT masscentre_detect [CODE]
        EXPORT montwell_detect [CODE]
        EXPORT detect_read_frame_RGB565 [CODE]
        EXPORT show_blocks [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT total_mass [DATA]
        IMPORT scn_zone [DATA]
        IMPORT det_x [DATA]
        IMPORT det_y [DATA]
        IMPORT const_block [DATA]
        IMPORT Window [CODE]
        IMPORT LCD_SetCursor [CODE]
        IMPORT GUI_Text [CODE]
        IMPORT fps_aux [DATA]
        IMPORT cd_R [DATA]
        IMPORT umbral [DATA]
        IMPORT cd_G [DATA]
        IMPORT cd_B [DATA]
        IMPORT color_detect [DATA]
        IMPORT conversor_IaS [CODE]
        IMPORT delay_read [DATA]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
