; generated by ARM C/C++ Compiler, 4.1 [Build 791]
; commandline ArmCC [--debug -c --asm -oov7670_read2.o --depend=ov7670_read2.d --cpu=Cortex-M3 --apcs=interwork -O0 -IC:\Keil\ARM\CMSIS\Include -IC:\Keil\ARM\INC\NXP\LPC17xx --omf_browse=ov7670_read2.crf OV7670\OV7670_read2.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

read_window_RGB565 PROC
        PUSH     {r4-r12,lr}
        MOV      r6,r0
        MOV      r7,r1
        MOV      r8,#0
        MOV      r5,r8
        MOV      r9,r5
        MOV      r4,r5
        NOP      
        NOP      
        MOV      r0,#0x14
        SDIV     r0,r7,r0
        RSB      r0,r0,#0xc
        ADD      r0,r0,r0,LSL #2
        LSL      r10,r0,#2
        MOV      r0,#0x14
        SDIV     r11,r6,r0
        MOV      r1,#0
        MOV      r0,r1
        BL       LCD_SetCursor
        SUB      r0,r10,#1
        UXTH     r3,r0
        ADD      r0,r11,r11,LSL #2
        MOVS     r1,#1
        ADD      r0,r1,r0,LSL #2
        LDR      r1,|L1.1096|
        LDRH     r1,[r1,#0]  ; MAX_X
        SUBS     r0,r1,r0
        UXTH     r2,r0
        MOVS     r1,#0
        MOV      r0,r1
        BL       Window
        LDR      r0,|L1.1100|
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x20000000
        LDR      r1,|L1.1100|
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x40000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        BIC      r0,r0,#0x1000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        ORR      r0,r0,#0x20000000
        STR      r0,[r1,#0x10]
        MOV      r0,r1
        LDR      r0,[r0,#0x10]
        ORR      r0,r0,#0x40000000
        STR      r0,[r1,#0x10]
        LDR      r0,|L1.1104|
        LDR      r0,[r0,#0]  ; fps_aux
        ADD      r0,r0,#1
        LDR      r1,|L1.1104|
        STR      r0,[r1,#0]  ; fps_aux
        B        |L1.1524|
|L1.228|
        MOV      r5,#0
        B        |L1.1040|
|L1.234|
        LDR      r0,|L1.1100|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.1100|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        ADD      r5,r5,#1
|L1.1040|
        CMP      r5,r11
        BCC      |L1.234|
        B        |L1.1514|
|L1.1048|
        MOV      r9,#0
        B        |L1.1502|
|L1.1054|
        LDR      r0,|L1.1100|
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        LDR      r1,|L1.1100|
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        B        |L1.1108|
        DCW      0x0000
|L1.1096|
        DCD      MAX_X
|L1.1100|
        DCD      0x2009c000
|L1.1104|
        DCD      fps_aux
|L1.1108|
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        MOV      r0,#0x100
        STR      r0,[r1,#0x5c]
        MOV      r0,#0x28000000
        STR      r0,[r1,#0x3c]
        MOV      r0,#0x22
        STR      r0,[r1,#0x54]
        MOV      r0,#0
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,#0x100
        STR      r0,[r1,#0x5c]
        STR      r0,[r1,#0x5c]
        MOV      r0,#0x8000000
        STR      r0,[r1,#0x38]
        UXTB     r0,r4
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        UXTB     r0,r4
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        UXTB     r0,r4
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        UXTB     r0,r4
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        LSL      r4,r0,#8
        MOV      r0,r1
        LDR      r0,[r0,#0x1c]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x1c]
        MOV      r0,r1
        LDR      r0,[r0,#0x18]
        ORR      r0,r0,#0x1000000
        STR      r0,[r1,#0x18]
        MOV      r0,r1
        LDR      r0,[r0,#0x34]
        UBFX     r0,r0,#18,#8
        ORR      r4,r0,r4
        UXTB     r0,r4
        STR      r0,[r1,#0x54]
        MOV      r0,#0x7f8000
        AND      r0,r0,r4,LSL #7
        STR      r0,[r1,#0x14]
        MOV      r0,#0x10000000
        STR      r0,[r1,#0x3c]
        STR      r0,[r1,#0x38]
        ADD      r9,r9,#1
|L1.1502|
        CMP      r9,#4
        BCC      |L1.1054|
        ADD      r5,r5,#1
|L1.1514|
        CMP      r5,#0x10
        BCC      |L1.1048|
        ADD      r8,r8,#1
|L1.1524|
        CMP      r8,r10
        BCC      |L1.228|
        POP      {r4-r12,pc}
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "OV7670\\OV7670_read2.c"
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___14_OV7670_read2_c_3d9f7d14____REV16|
#line 114 "C:\\Keil\\ARM\\CMSIS\\Include\\core_cmInstr.h"
|__asm___14_OV7670_read2_c_3d9f7d14____REV16| PROC
#line 115

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.emb_text||, CODE, READONLY
	THUMB
	EXPORT |__asm___14_OV7670_read2_c_3d9f7d14____REVSH|
#line 128
|__asm___14_OV7670_read2_c_3d9f7d14____REVSH| PROC
#line 129

 revsh r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT read_window_RGB565 [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT LCD_SetCursor [CODE]
        IMPORT Window [CODE]
        IMPORT MAX_X [DATA]
        IMPORT fps_aux [DATA]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
